// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjvNUQlLy7fvFqMSkaxC1rem6Briw0u6Q',
    appId: '1:415564274636:web:360934676713b95f3adb69',
    messagingSenderId: '415564274636',
    projectId: 'easy-lesson',
    authDomain: 'easy-lesson.firebaseapp.com',
    storageBucket: 'easy-lesson.appspot.com',
    measurementId: 'G-4NYR3P0PS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACGl9ju3W9Sjmm78hCq1SG0Fh8ioC_uQI',
    appId: '1:415564274636:android:ffd4cdc55b2ec09c3adb69',
    messagingSenderId: '415564274636',
    projectId: 'easy-lesson',
    storageBucket: 'easy-lesson.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUgToJXV-VLC8tPl-tK4NEo2oSv04Pdho',
    appId: '1:415564274636:ios:5004f84870e3d0ae3adb69',
    messagingSenderId: '415564274636',
    projectId: 'easy-lesson',
    storageBucket: 'easy-lesson.appspot.com',
    iosBundleId: 'com.example.webappDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUgToJXV-VLC8tPl-tK4NEo2oSv04Pdho',
    appId: '1:415564274636:ios:269aa388a313b4e23adb69',
    messagingSenderId: '415564274636',
    projectId: 'easy-lesson',
    storageBucket: 'easy-lesson.appspot.com',
    iosBundleId: 'com.example.webappDemo.RunnerTests',
  );
}
